<a href="https://colab.research.google.com/github/cwerries/IANNWTF_Group_14_Submissions/blob/master/textGenerationWithNietzsche_HW_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q tensorflow_text
!pip install -q sentencepiece
import tensorflow as tf
import tensorflow_text as tf_txt
import tqdm.notebook as note
import sentencepiece as sp
import io
import datetime

In [2]:
# load tensorboard extension
%load_ext tensorboard

## Hyperparameters


In [3]:
# Hyperparameters
VOCAB_SIZE = 5000       # 2000 - 7000
SEQUEN_LEN = 30     # m = lenght of input sequence
SHUFFLE_SIZE = 1000
BATCH_SIZE = 50
EMBED_DIM = 128          # 64 - 256
NUM_HEADS = 2          # 2-4
TOP_K = 50
EPOCH_SIZE = 600

# 4.1 The dataset, preprocessing and tokenization

In [4]:
# path "Beyond Good and Evil"
path = tf.keras.utils.get_file("nietzsche.txt", origin="https://s3.amazonaws.com/text-datasets/nietzsche.txt")
# load txt as string
text = open(path).read()

# train the SentencePiece tokenizer
sp.SentencePieceTrainer.train(
    input=path, model_prefix='tokenizer_model', model_type="unigram", vocab_size=VOCAB_SIZE)

# deserialize the model
trained_tokenizer_model = tf.io.gfile.GFile('tokenizer_model.model', "rb").read()
# load the model as a tokenizer 
tokenizer = tf_txt.SentencepieceTokenizer(
    model=trained_tokenizer_model, out_type=tf.int32, nbest_size=-1, alpha=1, reverse=False,
    add_bos=False, add_eos=False, return_nbest=False, name=None
)

# tokenize the str
tokens = tokenizer.tokenize(text)

# create all possible slices of m+1 
token_windows = tf_txt.sliding_window(data=tokens, width=SEQUEN_LEN + 1)

# create training data from tokenized text
token_ds = tf.data.Dataset.from_tensor_slices(token_windows)
# create targets
token_ds = token_ds.map(lambda x: (x[:SEQUEN_LEN], x[SEQUEN_LEN:SEQUEN_LEN+1]))
# shuffle, batch ds
token_ds = token_ds.shuffle(SHUFFLE_SIZE).batch(BATCH_SIZE)

## 4.2/3 The model 

In [5]:
class Embedd_Layer(tf.keras.layers.Layer):
    def __init__(self):
        super(Embedd_Layer, self).__init__()
        # embedding of token indices
        self.embedding_voc = tf.keras.layers.Embedding(input_dim=VOCAB_SIZE, output_dim=EMBED_DIM) 
        # embedding of token position  (positional embedding)
        self.embedding_pos = tf.keras.layers.Embedding(input_dim=SEQUEN_LEN, output_dim=EMBED_DIM)
    

    def call(self, x):
        x = self.embedding_voc(x)
        y = self.embedding_pos(tf.range(0,SEQUEN_LEN))
        return  y + x 

In [6]:
class TransformerBlock(tf.keras.layers.Layer):
    def __init__(self):
        super(TransformerBlock, self).__init__()

        self.mha = tf.keras.layers.MultiHeadAttention(num_heads=NUM_HEADS, key_dim=EMBED_DIM)

        self.dense_1 = tf.keras.layers.Dense(units=32, activation="relu") # 32 - 256 units
        self.dense_2 = tf.keras.layers.Dense(units=EMBED_DIM)
    
        self.dropout_1 = tf.keras.layers.Dropout(rate=0.1)
        self.dropout_2 = tf.keras.layers.Dropout(rate=0.1)

        self.norm_1 = tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.norm_2 = tf.keras.layers.LayerNormalization(epsilon=1e-6)


    def call(self, x):
        mha_out = self.mha(x, x)
        drop_out = self.dropout_2(mha_out)
        ln_out = self.norm_1(x + drop_out)
        dns_out = self.dense_1(ln_out)
        dns_out = self.dense_2(dns_out)
        drop_out = self.dropout_2(dns_out)
        y = self.norm_2(ln_out+drop_out)
        return y

In [7]:
class Transformer(tf.keras.Model):
    def __init__(self, tokenizer):
        super(Transformer, self).__init__()
        self.tokenizer = tokenizer
        self.optimizer = tf.keras.optimizers.Adam()
        self.loss_func = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

        self.metrics_list = [
                        tf.keras.metrics.Mean(name="loss"),
                        tf.keras.metrics.CategoricalAccuracy(name="acc"),
                        tf.keras.metrics.TopKCategoricalAccuracy(k=3,name="top-3-acc") 
                        ]

        self.layer_embedd = Embedd_Layer()
        self.layer_trnsfrm = TransformerBlock()
        self.pool = tf.keras.layers.GlobalAvgPool1D()
        self.dense = tf.keras.layers.Dense(units=VOCAB_SIZE)


    def call(self, x):      
        x = self.layer_embedd(x)
        x = self.layer_trnsfrm(x)
        x = self.pool(x)
        x = self.dense(x)
        return x


    def reset_metrics(self):
        for metric in self.metrics:
            metric.reset_states()
            

    @tf.function
    def train_step(self, data):       
        x, targets = data

        with tf.GradientTape() as tape:
            predictions = self(x)
            loss = self.loss_func(targets, predictions) + tf.reduce_sum(self.losses)
        
        gradients = tape.gradient(loss, self.trainable_variables)
        self.optimizer.apply_gradients(zip(gradients, self.trainable_variables))
        
        # update loss metric
        self.metrics[0].update_state(loss)
            
        # for all metrics except loss, update states (accuracy etc.)
        for metric in self.metrics[1:]:
            metric.update_state(targets,predictions)

        # Return a dictionary mapping metric names to current value
        return {m.name: m.result() for m in self.metrics}


    def generate_text(self, prompt, k_generate=5):
        #tokenize, add dimension and pad prompt
        tokenized = self.tokenizer.tokenize(prompt)
        len =  tokenized.shape[0]
        tokenized = tf.expand_dims(tokenized, axis=0)
        tokenized = tf.pad(tokenized, [[0,0], [SEQUEN_LEN - len,0]], "CONSTANT", constant_values=0)

        for _ in range(k_generate):
            # random next token
            logits, indices = tf.math.top_k(self(tokenized), k=TOP_K, sorted=True)
            sample = tf.random.categorical(tf.cast(indices, tf.float32), 1, dtype=tf.int32)
            # add new word to prompt
            tokenized = tf.concat((tokenized, sample), axis=1)
            # truncate beginning of prompt
            tokenized = tf.slice(tokenized, [0, 1], [1, SEQUEN_LEN])

        return self.tokenizer.detokenize(tokenized[:,-len-k_generate:])

# 4.4 The training loop


In [8]:
model = Transformer(tokenizer)

# Define where to save the log
hyperparameter_string = "VOCAB_SIZE-5000,SEQUEN_LEN-20,SHUFFLE_SIZE-1000,BATCH_SIZE-50,EMBED_DIM-128,NUM_HEADS-3"
current_time = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

# load tensorboard extension
log_path = f"logs/{hyperparameter_string}/{current_time}/train"
summary_writer = tf.summary.create_file_writer(log_path)

In [ ]:
for epoch in range(EPOCH_SIZE):
    
    print(f"Epoch {epoch}:")
    
    # Training:
    
    for data in note.tqdm(token_ds, position=0, leave=True):
        metrics = model.train_step(data)
    
    # print the metrics
    print([f"{key}: {value}" for (key, value) in zip(list(metrics.keys()), list(metrics.values()))])
    

    # Generate:
    prompt = "Yesterday I met with friends, we played and had a lot of fun. Now I am tired and would like "
    k_generate=5
    new_text = model.generate_text(prompt, k_generate=k_generate)
    print("Generated Text:", new_text, "\n")

     # logging the validation metrics to the log file which is used by tensorboard
    with summary_writer.as_default():
        for metric in model.metrics:
            tf.summary.scalar(f"{metric.name}", metric.result(), step=epoch)
        tf.summary.text(f"samplesizze{k_generate}", new_text, step=epoch)
    # reset all metrics (requires a reset_metrics method in the model)
    model.reset_metrics()


    

Epoch 0:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 6.16452693939209', 'acc: 0.009516403079032898', 'top-3-acc: 0.023246606811881065']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like: an all who have'], shape=(1,), dtype=string) 

Epoch 1:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 5.466800212860107', 'acc: 0.010583993047475815', 'top-3-acc: 0.020284218713641167']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like has we" this all'], shape=(1,), dtype=string) 

Epoch 2:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 5.202606678009033', 'acc: 0.008470023050904274', 'top-3-acc: 0.01527149323374033']
Generated Text: tf.Tensor([b'met with friends, we played and had a lot of fun. Now I am tired and would like their an foring at'], shape=(1,), dtype=string) 

Epoch 3:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 5.030490875244141', 'acc: 0.0073317307978868484', 'top-3-acc: 0.013532239943742752']
Generated Text: tf.Tensor([b'met with friends, we played and had a lot of fun. Now I am tired and would like their a his ory'], shape=(1,), dtype=string) 

Epoch 4:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 4.896561622619629', 'acc: 0.007063065655529499', 'top-3-acc: 0.012174773961305618']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likeyy have we,'], shape=(1,), dtype=string) 

Epoch 5:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 4.777190685272217', 'acc: 0.00615101819857955', 'top-3-acc: 0.011503110639750957']
Generated Text: tf.Tensor([b'met with friends, we played and had a lot of fun. Now I am tired and would like one havey theiring'], shape=(1,), dtype=string) 

Epoch 6:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 4.667699337005615', 'acc: 0.005748020485043526', 'top-3-acc: 0.01073953602463007']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like this-- not hasly'], shape=(1,), dtype=string) 

Epoch 7:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 4.560811519622803', 'acc: 0.0052036200650036335', 'top-3-acc: 0.010152715258300304']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like-s a be'], shape=(1,), dtype=string) 

Epoch 8:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 4.460017681121826', 'acc: 0.004913744516670704', 'top-3-acc: 0.009523472748696804']
Generated Text: tf.Tensor([b'met with friends, we played and had a lot of fun. Now I am tired and would like not at": one'], shape=(1,), dtype=string) 

Epoch 9:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 4.364366054534912', 'acc: 0.004560237750411034', 'top-3-acc: 0.009389140643179417']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likeing have-- a'], shape=(1,), dtype=string) 

Epoch 10:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 4.274470806121826', 'acc: 0.004341063555330038', 'top-3-acc: 0.00906391441822052']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like their or he theiry'], shape=(1,), dtype=string) 

Epoch 11:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 4.188514709472656', 'acc: 0.004319853149354458', 'top-3-acc: 0.008378110826015472']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like all their and his their'], shape=(1,), dtype=string) 

Epoch 12:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 4.104548454284668', 'acc: 0.004150169901549816', 'top-3-acc: 0.008243778720498085']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like who all aed we'], shape=(1,), dtype=string) 

Epoch 13:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 4.023243427276611', 'acc: 0.004100678954273462', 'top-3-acc: 0.008180147036910057']
Generated Text: tf.Tensor([b'met with friends, we played and had a lot of fun. Now I am tired and would like one that all or has'], shape=(1,), dtype=string) 

Epoch 14:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 3.94488263130188', 'acc: 0.003810803173109889', 'top-3-acc: 0.007946833036839962']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likely-: has'], shape=(1,), dtype=string) 

Epoch 15:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 3.8675711154937744', 'acc: 0.003655260195955634', 'top-3-acc: 0.007614536210894585']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would liket hee are is'], shape=(1,), dtype=string) 

Epoch 16:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 3.7906928062438965', 'acc: 0.003429015865549445', 'top-3-acc: 0.007289309985935688']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like their the--ee'], shape=(1,), dtype=string) 

Epoch 17:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 3.7174627780914307', 'acc: 0.0032805430237203836', 'top-3-acc: 0.007232748903334141']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like nott:" "'], shape=(1,), dtype=string) 

Epoch 18:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 3.6445722579956055', 'acc: 0.003181561129167676', 'top-3-acc: 0.007246889173984528']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likee"; the at'], shape=(1,), dtype=string) 

Epoch 19:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 3.571932792663574', 'acc: 0.0031037896405905485', 'top-3-acc: 0.006872172001749277']
Generated Text: tf.Tensor([b'met with friends, we played and had a lot of fun. Now I am tired and would like their be" man"'], shape=(1,), dtype=string) 

Epoch 20:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 3.5019946098327637', 'acc: 0.002870475174859166', 'top-3-acc: 0.006949943490326405']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likeing,: nott'], shape=(1,), dtype=string) 

Epoch 21:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 3.431837320327759', 'acc: 0.003026018152013421', 'top-3-acc: 0.006978224031627178']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likey of this is this'], shape=(1,), dtype=string) 

Epoch 22:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 3.3632864952087402', 'acc: 0.003026018152013421', 'top-3-acc: 0.007034785114228725']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likee their het who'], shape=(1,), dtype=string) 

Epoch 23:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 3.2971434593200684', 'acc: 0.002693721791729331', 'top-3-acc: 0.006766119971871376']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likeed" man an which'], shape=(1,), dtype=string) 

Epoch 24:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 3.2306361198425293', 'acc: 0.002778563415631652', 'top-3-acc: 0.006674208212643862']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like"yy. have'], shape=(1,), dtype=string) 

Epoch 25:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 3.1676902770996094', 'acc: 0.002729072468355298', 'top-3-acc: 0.006787330377846956']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like; it who an \xe2\x81\x87 '], shape=(1,), dtype=string) 

Epoch 26:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 3.1041147708892822', 'acc: 0.002707862062379718', 'top-3-acc: 0.006730769295245409']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like which are---- which'], shape=(1,), dtype=string) 

Epoch 27:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 3.042131185531616', 'acc: 0.002693721791729331', 'top-3-acc: 0.006801470648497343']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like are- ity not'], shape=(1,), dtype=string) 

Epoch 28:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.9792568683624268', 'acc: 0.0026513009797781706', 'top-3-acc: 0.006561086047440767']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like one--;"y'], shape=(1,), dtype=string) 

Epoch 29:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.9230895042419434', 'acc: 0.002623020438477397', 'top-3-acc: 0.006398472934961319']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like it his , who'], shape=(1,), dtype=string) 

Epoch 30:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.8631908893585205', 'acc: 0.0025311086792498827', 'top-3-acc: 0.006568156182765961']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likeing in for of this'], shape=(1,), dtype=string) 

Epoch 31:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.8048384189605713', 'acc: 0.0025593892205506563', 'top-3-acc: 0.006624717265367508']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would liked for his it we'], shape=(1,), dtype=string) 

Epoch 32:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.7494072914123535', 'acc: 0.002573529491201043', 'top-3-acc: 0.006327771581709385']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like man thisy:-'], shape=(1,), dtype=string) 

Epoch 33:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.6898398399353027', 'acc: 0.002432126784697175', 'top-3-acc: 0.006532805506139994']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like at their  be are'], shape=(1,), dtype=string) 

Epoch 34:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.636735439300537', 'acc: 0.0024038462433964014', 'top-3-acc: 0.006674208212643862']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like not at not; his'], shape=(1,), dtype=string) 

Epoch 35:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.583632707595825', 'acc: 0.0024533371906727552', 'top-3-acc: 0.0065257353708148']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likey or witht have'], shape=(1,), dtype=string) 

Epoch 36:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.5277462005615234', 'acc: 0.0022695136722177267', 'top-3-acc: 0.006455034017562866']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like his man alleded'], shape=(1,), dtype=string) 

Epoch 37:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.4735751152038574', 'acc: 0.0023897059727460146', 'top-3-acc: 0.006561086047440767']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like an-- who has are'], shape=(1,), dtype=string) 

Epoch 38:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.4249231815338135', 'acc: 0.002326074754819274', 'top-3-acc: 0.0065257353708148']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likee thiss with that'], shape=(1,), dtype=string) 

Epoch 39:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.3729310035705566', 'acc: 0.0022836539428681135', 'top-3-acc: 0.006780260242521763']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like-- thedd who'], shape=(1,), dtype=string) 

Epoch 40:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.3259148597717285', 'acc: 0.002290724078193307', 'top-3-acc: 0.006426753476262093']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like : their it have'], shape=(1,), dtype=string) 

Epoch 41:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.277279853820801', 'acc: 0.002205882454290986', 'top-3-acc: 0.006433823611587286']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like and-- havey'], shape=(1,), dtype=string) 

Epoch 42:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.2294979095458984', 'acc: 0.0021988123189657927', 'top-3-acc: 0.006660067941993475']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like a is their and a'], shape=(1,), dtype=string) 

Epoch 43:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.1847805976867676', 'acc: 0.0021563915070146322', 'top-3-acc: 0.0065469457767903805']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likes of his; or'], shape=(1,), dtype=string) 

Epoch 44:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.1397705078125', 'acc: 0.0022624435368925333', 'top-3-acc: 0.006363122258335352']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like that in an. for'], shape=(1,), dtype=string) 

Epoch 45:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.0995702743530273', 'acc: 0.0021422512363642454', 'top-3-acc: 0.006490384694188833']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like a to nots he'], shape=(1,), dtype=string) 

Epoch 46:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.056157112121582', 'acc: 0.002205882454290986', 'top-3-acc: 0.006327771581709385']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like., their have their'], shape=(1,), dtype=string) 

Epoch 47:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 2.0182971954345703', 'acc: 0.0021422512363642454', 'top-3-acc: 0.0068085407838225365']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like and or and \xe2\x81\x87 .'], shape=(1,), dtype=string) 

Epoch 48:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.9751272201538086', 'acc: 0.002205882454290986', 'top-3-acc: 0.006638857536017895']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like for this an we,'], shape=(1,), dtype=string) 

Epoch 49:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.9420287609100342', 'acc: 0.0021563915070146322', 'top-3-acc: 0.0065822964534163475']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likely \xe2\x81\x87  to have and'], shape=(1,), dtype=string) 

Epoch 50:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.9056180715560913', 'acc: 0.002149321371689439', 'top-3-acc: 0.006610576994717121']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like mand at \xe2\x81\x87  that'], shape=(1,), dtype=string) 

Epoch 51:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.8674745559692383', 'acc: 0.002014988800510764', 'top-3-acc: 0.006596436724066734']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like " ones not one'], shape=(1,), dtype=string) 

Epoch 52:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.8334215879440308', 'acc: 0.002290724078193307', 'top-3-acc: 0.006667138077318668']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likeeed ane '], shape=(1,), dtype=string) 

Epoch 53:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.7983996868133545', 'acc: 0.0020574096124619246', 'top-3-acc: 0.0065469457767903805']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like have" of we he'], shape=(1,), dtype=string) 

Epoch 54:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.7652195692062378', 'acc: 0.0021281109657138586', 'top-3-acc: 0.006327771581709385']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like all ae has'], shape=(1,), dtype=string) 

Epoch 55:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.7337398529052734', 'acc: 0.002205882454290986', 'top-3-acc: 0.0065822964534163475']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like man not who to,'], shape=(1,), dtype=string) 

Epoch 56:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.7049098014831543', 'acc: 0.002029129071161151', 'top-3-acc: 0.006759049836546183']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like"- and his who'], shape=(1,), dtype=string) 

Epoch 57:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.6740758419036865', 'acc: 0.0021281109657138586', 'top-3-acc: 0.00681561091914773']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like who the, itly'], shape=(1,), dtype=string) 

Epoch 58:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.6453031301498413', 'acc: 0.0021634616423398256', 'top-3-acc: 0.006603506859391928']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like one with has be have'], shape=(1,), dtype=string) 

Epoch 59:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.6165896654129028', 'acc: 0.0020220589358359575', 'top-3-acc: 0.006766119971871376']
Generated Text: tf.Tensor([b'met with friends, we played and had a lot of fun. Now I am tired and would like all;ed in"'], shape=(1,), dtype=string) 

Epoch 60:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.588101863861084', 'acc: 0.0021422512363642454', 'top-3-acc: 0.0068438914604485035']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like" man who not one'], shape=(1,), dtype=string) 

Epoch 61:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.5632480382919312', 'acc: 0.002064479747787118', 'top-3-acc: 0.006539875641465187']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like the:-- man'], shape=(1,), dtype=string) 

Epoch 62:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.5351788997650146', 'acc: 0.0019725679885596037', 'top-3-acc: 0.0067731901071965694']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like whoed which it man'], shape=(1,), dtype=string) 

Epoch 63:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.5094720125198364', 'acc: 0.002113970695063472', 'top-3-acc: 0.006801470648497343']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like not who man it-'], shape=(1,), dtype=string) 

Epoch 64:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.483637809753418', 'acc: 0.002121040830388665', 'top-3-acc: 0.006476244423538446']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like we or andd has'], shape=(1,), dtype=string) 

Epoch 65:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.458017349243164', 'acc: 0.002121040830388665', 'top-3-acc: 0.006334841717034578']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like have. het--'], shape=(1,), dtype=string) 

Epoch 66:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.4332005977630615', 'acc: 0.0021422512363642454', 'top-3-acc: 0.006589366588741541']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like and with at man at'], shape=(1,), dtype=string) 

Epoch 67:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.410819411277771', 'acc: 0.0021069005597382784', 'top-3-acc: 0.006313631311058998']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like all at who for;'], shape=(1,), dtype=string) 

Epoch 68:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.3880598545074463', 'acc: 0.002149321371689439', 'top-3-acc: 0.006631787400692701']
Generated Text: tf.Tensor([b'met with friends, we played and had a lot of fun. Now I am tired and would like att not has all'], shape=(1,), dtype=string) 

Epoch 69:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.3657526969909668', 'acc: 0.0020432693418115377', 'top-3-acc: 0.0066529978066682816']
Generated Text: tf.Tensor([b'met with friends, we played and had a lot of fun. Now I am tired and would likelyt for one it'], shape=(1,), dtype=string) 

Epoch 70:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.3494454622268677', 'acc: 0.002064479747787118', 'top-3-acc: 0.0065822964534163475']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like has we: whoed'], shape=(1,), dtype=string) 

Epoch 71:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.3281306028366089', 'acc: 0.0020079186651855707', 'top-3-acc: 0.006631787400692701']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like have have all of;'], shape=(1,), dtype=string) 

Epoch 72:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.3064022064208984', 'acc: 0.0020008485298603773', 'top-3-acc: 0.006568156182765961']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like we-- we man or'], shape=(1,), dtype=string) 

Epoch 73:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.2830134630203247', 'acc: 0.0020079186651855707', 'top-3-acc: 0.006638857536017895']
Generated Text: tf.Tensor([b'met with friends, we played and had a lot of fun. Now I am tired and would like": their at"'], shape=(1,), dtype=string) 

Epoch 74:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.2672189474105835', 'acc: 0.0020220589358359575', 'top-3-acc: 0.006603506859391928']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like their thating it has'], shape=(1,), dtype=string) 

Epoch 75:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.247589111328125', 'acc: 0.0020361992064863443', 'top-3-acc: 0.00646210415288806']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likely..d or'], shape=(1,), dtype=string) 

Epoch 76:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.2281571626663208', 'acc: 0.0020361992064863443', 'top-3-acc: 0.006327771581709385']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like" this withse'], shape=(1,), dtype=string) 

Epoch 77:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.2151390314102173', 'acc: 0.0020079186651855707', 'top-3-acc: 0.006490384694188833']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like wely; we of'], shape=(1,), dtype=string) 

Epoch 78:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.1922073364257812', 'acc: 0.002014988800510764', 'top-3-acc: 0.006334841717034578']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like who;eded it'], shape=(1,), dtype=string) 

Epoch 79:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.175964593887329', 'acc: 0.0020432693418115377', 'top-3-acc: 0.006532805506139994']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like one of s,'], shape=(1,), dtype=string) 

Epoch 80:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.1617188453674316', 'acc: 0.002099830424413085', 'top-3-acc: 0.006221719551831484']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like- the- be'], shape=(1,), dtype=string) 

Epoch 81:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.1436039209365845', 'acc: 0.0020361992064863443', 'top-3-acc: 0.006455034017562866']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like have have which; and'], shape=(1,), dtype=string) 

Epoch 82:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.128627896308899', 'acc: 0.002029129071161151', 'top-3-acc: 0.006334841717034578']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like nots have;;'], shape=(1,), dtype=string) 

Epoch 83:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.119622826576233', 'acc: 0.001979638123884797', 'top-3-acc: 0.00646210415288806']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likeee ory;'], shape=(1,), dtype=string) 

Epoch 84:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.0996131896972656', 'acc: 0.0020220589358359575', 'top-3-acc: 0.006228789687156677']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like has not " for or'], shape=(1,), dtype=string) 

Epoch 85:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.0878349542617798', 'acc: 0.0020008485298603773', 'top-3-acc: 0.0062500000931322575']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like are and whoing this'], shape=(1,), dtype=string) 

Epoch 86:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.0738646984100342', 'acc: 0.002064479747787118', 'top-3-acc: 0.006341911852359772']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like an" it his be'], shape=(1,), dtype=string) 

Epoch 87:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.0597018003463745', 'acc: 0.0020361992064863443', 'top-3-acc: 0.006087386980652809']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like " he of beed'], shape=(1,), dtype=string) 

Epoch 88:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.0439510345458984', 'acc: 0.0019725679885596037', 'top-3-acc: 0.006327771581709385']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like" their withd "'], shape=(1,), dtype=string) 

Epoch 89:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.0351310968399048', 'acc: 0.002014988800510764', 'top-3-acc: 0.006384332664310932']
Generated Text: tf.Tensor([b'met with friends, we played and had a lot of fun. Now I am tired and would like all ort-- with'], shape=(1,), dtype=string) 

Epoch 90:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.0193536281585693', 'acc: 0.002085690153762698', 'top-3-acc: 0.006398472934961319']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like have-: his \xe2\x81\x87 '], shape=(1,), dtype=string) 

Epoch 91:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 1.0084620714187622', 'acc: 0.0020079186651855707', 'top-3-acc: 0.006476244423538446']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like their all at his his'], shape=(1,), dtype=string) 

Epoch 92:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.9961357712745667', 'acc: 0.001979638123884797', 'top-3-acc: 0.006709558889269829']
Generated Text: tf.Tensor([b'met with friends, we played and had a lot of fun. Now I am tired and would like wey or that at'], shape=(1,), dtype=string) 

Epoch 93:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.9850010871887207', 'acc: 0.002050339477136731', 'top-3-acc: 0.006455034017562866']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like" be have-d'], shape=(1,), dtype=string) 

Epoch 94:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.9755609035491943', 'acc: 0.0020008485298603773', 'top-3-acc: 0.0063207014463841915']
Generated Text: tf.Tensor([b'met with friends, we played and had a lot of fun. Now I am tired and would like with this are it their'], shape=(1,), dtype=string) 

Epoch 95:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.9650035500526428', 'acc: 0.0019654978532344103', 'top-3-acc: 0.006518665235489607']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like as all-t and'], shape=(1,), dtype=string) 

Epoch 96:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.9532660841941833', 'acc: 0.0020220589358359575', 'top-3-acc: 0.006426753476262093']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like" at his" all'], shape=(1,), dtype=string) 

Epoch 97:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.9397610425949097', 'acc: 0.0019442873308435082', 'top-3-acc: 0.0066529978066682816']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like forlye have"'], shape=(1,), dtype=string) 

Epoch 98:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.9292057156562805', 'acc: 0.0020786200184375048', 'top-3-acc: 0.006341911852359772']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like not:ed-- with'], shape=(1,), dtype=string) 

Epoch 99:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.9292541742324829', 'acc: 0.002050339477136731', 'top-3-acc: 0.006348981987684965']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likey who his this this'], shape=(1,), dtype=string) 

Epoch 100:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.9162837862968445', 'acc: 0.001979638123884797', 'top-3-acc: 0.006596436724066734']
Generated Text: tf.Tensor([b'met with friends, we played and had a lot of fun. Now I am tired and would like ly" and'], shape=(1,), dtype=string) 

Epoch 101:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.9062972664833069', 'acc: 0.0020432693418115377', 'top-3-acc: 0.006660067941993475']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like; a, he'], shape=(1,), dtype=string) 

Epoch 102:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.896218478679657', 'acc: 0.002029129071161151', 'top-3-acc: 0.0063207014463841915']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like has are haveedly'], shape=(1,), dtype=string) 

Epoch 103:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.8933854699134827', 'acc: 0.0020715498831123114', 'top-3-acc: 0.006122737657278776']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like not one ofed with'], shape=(1,), dtype=string) 

Epoch 104:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.8804488778114319', 'acc: 0.0020079186651855707', 'top-3-acc: 0.006341911852359772']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would liket be an or an'], shape=(1,), dtype=string) 

Epoch 105:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.8733231425285339', 'acc: 0.0020079186651855707', 'top-3-acc: 0.006363122258335352']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like;: one is we'], shape=(1,), dtype=string) 

Epoch 106:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.863241970539093', 'acc: 0.002014988800510764', 'top-3-acc: 0.00650452496483922']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like and is man one their'], shape=(1,), dtype=string) 

Epoch 107:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.8572338223457336', 'acc: 0.0019867082592099905', 'top-3-acc: 0.006433823611587286']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likey a " his we'], shape=(1,), dtype=string) 

Epoch 108:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.8476473689079285', 'acc: 0.0020432693418115377', 'top-3-acc: 0.005931844003498554']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like an.se with'], shape=(1,), dtype=string) 

Epoch 109:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.8398545384407043', 'acc: 0.002014988800510764', 'top-3-acc: 0.006087386980652809']
Generated Text: tf.Tensor([b'met with friends, we played and had a lot of fun. Now I am tired and would likelydly are and'], shape=(1,), dtype=string) 

Epoch 110:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.8444781303405762', 'acc: 0.0020715498831123114', 'top-3-acc: 0.006264140363782644']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like man an that" an'], shape=(1,), dtype=string) 

Epoch 111:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.824660062789917', 'acc: 0.0020220589358359575', 'top-3-acc: 0.006313631311058998']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like a  of which this'], shape=(1,), dtype=string) 

Epoch 112:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.8222002387046814', 'acc: 0.0019867082592099905', 'top-3-acc: 0.006370192393660545']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like this his theirted'], shape=(1,), dtype=string) 

Epoch 113:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.8159160017967224', 'acc: 0.0020786200184375048', 'top-3-acc: 0.006306561175733805']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would liket that have are one'], shape=(1,), dtype=string) 

Epoch 114:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.8106287717819214', 'acc: 0.0020220589358359575', 'top-3-acc: 0.00619343901053071']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like man are with all a'], shape=(1,), dtype=string) 

Epoch 115:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.8013071417808533', 'acc: 0.0019867082592099905', 'top-3-acc: 0.006200509145855904']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like d thisedy'], shape=(1,), dtype=string) 

Epoch 116:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.7960556745529175', 'acc: 0.001993778394535184', 'top-3-acc: 0.006348981987684965']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like we; an man their'], shape=(1,), dtype=string) 

Epoch 117:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.790891706943512', 'acc: 0.0019867082592099905', 'top-3-acc: 0.006419683340936899']
Generated Text: tf.Tensor([b'met with friends, we played and had a lot of fun. Now I am tired and would like thist it he this'], shape=(1,), dtype=string) 

Epoch 118:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.7889556884765625', 'acc: 0.0019867082592099905', 'top-3-acc: 0.005974264815449715']
Generated Text: tf.Tensor([b'met with friends, we played and had a lot of fun. Now I am tired and would like one thatt hass'], shape=(1,), dtype=string) 

Epoch 119:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.779198944568634', 'acc: 0.0020715498831123114', 'top-3-acc: 0.0062500000931322575']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likee. an one are'], shape=(1,), dtype=string) 

Epoch 120:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.7760472893714905', 'acc: 0.0020008485298603773', 'top-3-acc: 0.00648331455886364']
Generated Text: tf.Tensor([b'met with friends, we played and had a lot of fun. Now I am tired and would like have he is as--'], shape=(1,), dtype=string) 

Epoch 121:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.7733844518661499', 'acc: 0.002029129071161151', 'top-3-acc: 0.006115667521953583']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likeedy which notd'], shape=(1,), dtype=string) 

Epoch 122:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.7645336389541626', 'acc: 0.002014988800510764', 'top-3-acc: 0.006405543070286512']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would liket hely itd'], shape=(1,), dtype=string) 

Epoch 123:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.7627364993095398', 'acc: 0.0020220589358359575', 'top-3-acc: 0.006497454829514027']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like he who at ort'], shape=(1,), dtype=string) 

Epoch 124:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.7620940804481506', 'acc: 0.0020008485298603773', 'top-3-acc: 0.0066176471300423145']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like have his who this"'], shape=(1,), dtype=string) 

Epoch 125:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.7512762546539307', 'acc: 0.0020574096124619246', 'top-3-acc: 0.00648331455886364']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like"."e not'], shape=(1,), dtype=string) 

Epoch 126:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.743992030620575', 'acc: 0.002029129071161151', 'top-3-acc: 0.0063207014463841915']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likeyly all that man'], shape=(1,), dtype=string) 

Epoch 127:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.7452507019042969', 'acc: 0.0020008485298603773', 'top-3-acc: 0.006384332664310932']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like man at an are is'], shape=(1,), dtype=string) 

Epoch 128:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.7413243055343628', 'acc: 0.0019725679885596037', 'top-3-acc: 0.006334841717034578']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like this;ye man'], shape=(1,), dtype=string) 

Epoch 129:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.738959550857544', 'acc: 0.001993778394535184', 'top-3-acc: 0.00648331455886364']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like whodly all he'], shape=(1,), dtype=string) 

Epoch 130:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.7310173511505127', 'acc: 0.002014988800510764', 'top-3-acc: 0.0062146494165062904']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likeded all is an'], shape=(1,), dtype=string) 

Epoch 131:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.7287806272506714', 'acc: 0.002029129071161151', 'top-3-acc: 0.006363122258335352']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would likely;y we their'], shape=(1,), dtype=string) 

Epoch 132:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.7265625596046448', 'acc: 0.001993778394535184', 'top-3-acc: 0.0065115951001644135']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like ane has it and'], shape=(1,), dtype=string) 

Epoch 133:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.7261902093887329', 'acc: 0.0020432693418115377', 'top-3-acc: 0.006087386980652809']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like haveysly are'], shape=(1,), dtype=string) 

Epoch 134:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.7266420722007751', 'acc: 0.002029129071161151', 'top-3-acc: 0.0062853507697582245']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would liked all with theire'], shape=(1,), dtype=string) 

Epoch 135:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.716547966003418', 'acc: 0.0019867082592099905', 'top-3-acc: 0.006235859822481871']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like his not his he to'], shape=(1,), dtype=string) 

Epoch 136:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.7183276414871216', 'acc: 0.001993778394535184', 'top-3-acc: 0.006433823611587286']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like have "t ane'], shape=(1,), dtype=string) 

Epoch 137:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.7135984897613525', 'acc: 0.0020220589358359575', 'top-3-acc: 0.0060237557627260685']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would like havely;ee'], shape=(1,), dtype=string) 

Epoch 138:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.7099204063415527', 'acc: 0.001958427717909217', 'top-3-acc: 0.0065115951001644135']
Generated Text: tf.Tensor([b'I met with friends, we played and had a lot of fun. Now I am tired and would liked in not. an'], shape=(1,), dtype=string) 

Epoch 139:


  0%|          | 0/2829 [00:00<?, ?it/s]

['loss: 0.7084396481513977', 'acc: 0.0020432693418115377', 'top-3-acc: 0.006539875641465187']
Generated Text: tf.Tensor([b'met with friends, we played and had a lot of fun. Now I am tired and would like are with thee all'], shape=(1,), dtype=string) 

Epoch 140:


  0%|          | 0/2829 [00:00<?, ?it/s]

In [ ]:
# open the tensorboard to inspect the data for the 100 steps
%tensorboard --logdir logs/

In [ ]:
# save the model with a meaningful name
model.save_weights(f"saved_model_{hyperparameter_string}", save_format="tf")